USE pharmacovigilance_db;

SHOW TABLES;
DESCRIBE reports;
DESCRIBE drugs;
DESCRIBE reactions;
DESCRIBE products;
DESCRIBE orders;
DESCRIBE orderitems;
DESCRIBE productcategories;
DESCRIBE customers;
DESCRIBE categories;

SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_KEY
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'pharmacovigilance_db'
ORDER BY TABLE_NAME, ORDINAL_POSITION;

SELECT 
    TABLE_NAME,
    GROUP_CONCAT(
        COLUMN_NAME 
        ORDER BY ORDINAL_POSITION 
        SEPARATOR ', '
    ) AS COLUMNS
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'pharmacovigilance_db'
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;
